### PR TITLE
remove aws-sdk-promise

### PR DESCRIPTION
**Pull request by jhford**

### CODE REVIEW

**Comment by jhford** [comment]
this is the last holdout for https://github.com/taskcluster/taskcluster-base/pull/77 to be able to merge

**Comment by jhford** [comment]
Oh, and like lib-api, this doesn't require any special futzing with the actual code as we never actual read the result of the aws operations.

**Comment by jonasfj** [comment]
Why bump major version?

r+

**Comment by jonasfj** [comment]
So sad, we never landed this... I'll take another look..

**Pull request merged**
